[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         tail
    Path         /logs/nats-*/nats.log
    Path_Key     filename
    Tag          nats.logs
    Refresh_Interval 5

[INPUT]
    Name         nats
    Host         nats-1
    Port         4222
    Subscribe    $JS.EVENT.ADVISORY.STREAM.>
    Tag          nats.advisories

[OUTPUT]
    Name         loki
    Match        nats.logs
    Host         otel-lgtm
    Port         3100
    Labels       job=nats-cluster

[OUTPUT]
    Name         loki
    Match        nats.advisories
    Host         otel-lgtm
    Port         3100
    Labels       job=nats-stream-advisories

