[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         tail
    Path         /logs/nats-*/nats.log
    Path_Key     filename
    Tag          nats.*
    Refresh_Interval 5

[OUTPUT]
    Name         loki
    Match        nats.*
    Host         otel-lgtm
    Port         3100
    Labels       job=nats-cluster
